/// ============================================================
/// Author: Shaun Curtis, Cold Elm Coders
/// License: Use And Donate
/// If you use it, donate something to a charity somewhere
/// ============================================================
namespace Blazr.App.EntityFramework;

/// <summary>
/// Mediator Handler for executing commands against a Customer Entity in an Entity Framework Context
/// </summary>
public sealed record CustomerCommandHandler : IRequestHandler<CustomerCommandRequest, Return<CustomerId>>
{
    private readonly IMessageBus _messageBus;
    private readonly IDbContextFactory<InMemoryInvoiceTestDbContext> _factory;

    public CustomerCommandHandler(IDbContextFactory<InMemoryInvoiceTestDbContext> factory, IMessageBus messageBus)
    {
        _factory = factory;
        _messageBus = messageBus;
    }

    public async Task<Return<CustomerId>> HandleAsync(CustomerCommandRequest request, CancellationToken cancellationToken)
    {
        using var dbContext = _factory.CreateDbContext();

        // Get the record result
        var result = await dbContext
            .ExecuteCommandAsync<DboCustomer>(new CommandRequest<DboCustomer>(
                    Item: DboCustomer.Map(request.Item),
                    State: request.State
                ),
                cancellationToken);

        //If the result is successful, we publish the DmoCustomer to the message bus
        // and return the Id - this may have been generated by the database
        return result.Bind<DboCustomer, CustomerId>(record =>
            {
                var id = CustomerId.Load(record.CustomerID);
                _messageBus.Publish<DmoCustomer>(id);
                return ReturnT.Read(id);
            }
        );
    }
}
